const demoMachines = [
  {
    id: 'demo-tractor',
    name: 'Mahindra 575 DI',
    brand: 'Mahindra',
    category: 'TRACTOR',
    pricePerHour: 1250,
    horsepower: 47,
    imageUrl: '/machinery/demo-tractor.webp',
    latOffset: 0.003,
    lngOffset: 0.002,
  },
  {
    id: 'demo-tractor-jd',
    name: 'John Deere 5050D',
    brand: 'John Deere',
    category: 'TRACTOR',
    pricePerHour: 1450,
    horsepower: 50,
    imageUrl: '/machinery/demo-tractor.webp',
    latOffset: -0.002,
    lngOffset: 0.004,
  },
  {
    id: 'demo-tractor-swaraj',
    name: 'Swaraj 744 FE',
    brand: 'Swaraj',
    category: 'TRACTOR',
    pricePerHour: 1150,
    horsepower: 48,
    imageUrl: '/machinery/demo-tractor.webp',
    latOffset: 0.006,
    lngOffset: -0.002,
  },
  {
    id: 'demo-harvester',
    name: 'Preet Combine Harvester',
    brand: 'Preet',
    category: 'HARVESTER',
    pricePerHour: 2800,
    horsepower: 101,
    imageUrl: '/machinery/demo-harvester.webp',
    latOffset: -0.004,
    lngOffset: 0.004,
  },
  {
    id: 'demo-harvester-kubota',
    name: 'Kubota DC-68G Harvester',
    brand: 'Kubota',
    category: 'HARVESTER',
    pricePerHour: 2600,
    horsepower: 68,
    imageUrl: '/machinery/demo-harvester.webp',
    latOffset: 0.002,
    lngOffset: -0.006,
  },
  {
    id: 'demo-harvester-dasmesh',
    name: 'Dasmesh Paddy Harvester',
    brand: 'Dasmesh',
    category: 'HARVESTER',
    pricePerHour: 2450,
    horsepower: 76,
    imageUrl: '/machinery/demo-harvester.webp',
    latOffset: -0.007,
    lngOffset: -0.003,
  },
  {
    id: 'demo-rotavator',
    name: 'Shaktiman Rotavator',
    brand: 'Shaktiman',
    category: 'TILLAGE',
    pricePerHour: 750,
    horsepower: 40,
    imageUrl: '/machinery/demo-rotavator.webp',
    latOffset: 0.005,
    lngOffset: -0.003,
  },
  {
    id: 'demo-rotavator-fieldking',
    name: 'Fieldking Rotavator',
    brand: 'Fieldking',
    category: 'TILLAGE',
    pricePerHour: 700,
    horsepower: 35,
    imageUrl: '/machinery/demo-rotavator.webp',
    latOffset: -0.003,
    lngOffset: -0.006,
  },
  {
    id: 'demo-rotavator-maschio',
    name: 'Maschio Rotary Tiller',
    brand: 'Maschio',
    category: 'TILLAGE',
    pricePerHour: 825,
    horsepower: 45,
    imageUrl: '/machinery/demo-rotavator.webp',
    latOffset: 0.007,
    lngOffset: 0.005,
  },
];

const demoDrivers = [
  ['DEMO-DRIVER', 'Suresh Kumar', '+919000000003', 0.001, 0.001],
  ['DEMO-DRIVER-2', 'Arun Delivery', '+919000000005', 0.012, 0.009],
  ['DEMO-DRIVER-3', 'Karthik Transport', '+919000000006', -0.016, 0.011],
];

const demoOperators = [
  {
    id: 'demo-operator-tractor',
    name: 'Demo · Tractor and tillage operator',
    phone: '+919000000007',
    skills: ['TRACTOR', 'TILLAGE'],
    certification: 'Demonstration qualification — not a real credential',
    hourlyRate: 180,
  },
  {
    id: 'demo-operator-harvester',
    name: 'Demo · Harvester operator',
    phone: '+919000000008',
    skills: ['HARVESTER'],
    certification: 'Demonstration qualification — not a real credential',
    hourlyRate: 250,
  },
];

const machineData = (machine, ownerId, latitude, longitude) => ({
  name: machine.name,
  brand: machine.brand,
  category: machine.category,
  pricePerHour: machine.pricePerHour,
  pricePerDay: machine.pricePerHour * 6.5,
  horsepower: machine.horsepower,
  fuelType: 'Diesel',
  imageUrl: machine.imageUrl,
  description: 'Demonstration listing prepared for nearby booking and delivery workflow testing.',
  location: 'Demo pickup near your current farm',
  latitude: latitude + machine.latOffset,
  longitude: longitude + machine.lngOffset,
  ownerId,
  deliveryRadiusKm: 50,
  verificationStatus: 'VERIFIED',
  status: 'AVAILABLE',
  operatorAvailable: true,
  fuelLitresPerHour: machine.category === 'HARVESTER' ? 12 : 4,
  acresPerHour: machine.category === 'HARVESTER' ? 2.5 : 1,
});

module.exports = { demoMachines, demoDrivers, demoOperators, machineData };
